### ISSUE TITLE
“Preview” throws an exception when the standard of the problem is not entered. 

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/msadmin#25]
This should be more graceful, such as a warning or alike, as it can take a long time to figure out what is going on (Ivon, 10/4/18)

**Comment by mohit-surana** [comment]
Have tried using a question with the standard saved but still facing this issue.
e.g. http://rose.cs.umass.edu/msadmin/qauth/prob/edit/1780/

While investigating this issue (reproduced issue), I came across this error in /opt/tomcat8/logs/catalina.out :
Caused by: java.lang.InstantiationException: bean problem not found within scope
	at org.apache.jsp.quickAuthProblem_jsp._jspService(quickAuthProblem_jsp.java:129)

This is the file where the error occurs:
https://github.com/marshall62/mathspring/blob/master/woServer/resources/quickAuthProblem.jsp#L2

This is a possible solution:
https://stackoverflow.com/a/3029379/6649050
The answer mentions that changing "type" to "class" should fix the issue.

Neeraj and I are working on this.

**Comment by mohit-surana** [comment]
This was tested by Neeraj and it turns out that if a problem is "dead", this error will be observed.
If the problem is set to ready or testable, it should be fine.
