### ISSUE TITLE
Hint Order field is not maintained at authoring

### ISSUE THREAD

**Issue by perspegrity5** [marshall62/msadmin#43]
Hello all,

I just discovered that many hints created in recent months have Order of "-1".  There are 103 such hints in the system. There is no consistency RE which hint they are , e.g. Hint1, Hint5.... They are not "gives answer" hints in most cases.  In some cases there are several of these hints in the same problem.  Problem hint ordering may be problematic in recently created problems. e.g. 1677 -- I verified in MS that the order hints are given does not follow the Hint1, Hint2...sequence.   

Note that hints have a Name, e.g. Hint 2 and an Order, e.g. 2.  This is because in the past (and maybe in future) some hint names were descriptive, e.g. "remind about formula".

Some of these are Ready problems.  I don't think I should turn them off if they are quasi-working.  Ivon, should I?

FYI In looking at some I see that 1636 shows up blank in mathspring.org.

**Comment by mohit-surana** [comment]
It looks like when we add a new hint, and a modal window opens - we do not have a hintId yet and the code at [this line](https://github.com/marshall62/msadmin/blob/master/msadmin/static/js/qa/hints.js#L226) relies on us having a hintId. This causes the order to be set to -1 (not found). 

I am now looking at ways to refactor the logic so that we correctly keep track of the ordering.
